services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - internal
  backend:
    build: ./catnasta/api
    restart: always
    environment:
      - MONGO_URI=mongodb://root:secretpassword@mongo:27017
      - AUTH_SERVER_URL=http://192.168.0.101:8080
      - REALM=catnasta
      - CLIENT_ID=catnasta-api
      - CLIENT_SECRET=7M1JAv96bc1TGhu8ma310oxdVu5IdPUD
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - internal
      - external
  frontend:
    build: ./catnasta/frontend
    environment:
      - API=http://backend:5000
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - external
  postgres:
    image: postgres:16
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    networks:
      - internal-keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: keycloak
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - 8080:8080
    networks:
      - external
      - internal-keycloak
  user-frontend:
    build: ./fe/secure-frontend
    depends_on:
      - keycloak
    ports:
      - 80:4173
    networks:
      - external
    restart: always
  go-api:
    build: ./go-api
    ports:
      - 8081:8081
    networks:
      - external
    restart: always
    environment:
      - GIN_MOD=release
      - KEYCLOAK_SERICE=catnasta-api
      - KEYCLOAK_REALM=catnasta
      - KEYCLOAK_URL=http://keycloak:8080
      - API_URL=http://backend:5000
networks:
  internal:
  external:
  internal-keycloak:
